name: Documentation

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

  generate_docs:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    permissions:
      contents: write
      packages: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

#    - name: Build DocFxTocGenerator
#      run: |
#        cd submodules/docfx-companion-tools/src/DocFxTocGenerator
#        dotnet build -c Release

#    - name: Generate Table of Contents
#      run: |
#        cd docs
#        dotnet ../submodules/docfx-companion-tools/src/DocFxTocGenerator/bin/Release/net9.0/DocFxTocGenerator.dll -d . -o . --verbose

    - name: Generate Documentation
      uses: nunit/docfx-action@v4.0.0
      with:
        args: docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: documentation  # Use a different branch for documentation 